class Publisher < ActiveHash::Base
  self.data = [
      {id: 1, publisher: 'あいうえお館'}, {id: 2, publisher: '赤ちゃんとママ社'}, {id: 3, publisher: 'あかね書房'},
      {id: 4, publisher: '朝日新聞出版'}, {id: 5, publisher: '飛鳥新社'}, {id: 6, publisher: 'あすなろ書房'},
      {id: 7, publisher: 'アスラン書房'}, {id: 8, publisher: '梓書院'}, {id: 9, publisher: 'アノニマ・スタジオ'},
      {id: 10, publisher: 'アリス館'}, {id: 11, publisher: 'いずみ書房'}, {id: 12, publisher: 'いそっぷ社'},
      {id: 13, publisher: '岩崎書店'}, {id: 14, publisher: '岩波書店'}, {id: 15, publisher: 'インプレスブックス'},
      {id: 16, publisher: 'イースト・プレス'}, {id: 17, publisher: 'WAVE出版'}, {id: 18, publisher: 'エッセンシャル出版社'},
      {id: 19, publisher: 'NHK出版'}, {id: 20, publisher: '絵本館'}, {id: 21, publisher: 'えほんの杜'},
      {id: 22, publisher: 'エムオン・エンタテイメント'}, {id: 23, publisher: 'おむすび舎'}, {id: 24, publisher: '偕成社'},
      {id: 25, publisher: 'KADOKAWA'}, {id: 26, publisher: '河出書房新社'}, {id: 27, publisher: '学研'},
      {id: 28, publisher: '教育画劇'}, {id: 29, publisher: '金の星社'}, {id: 30, publisher: 'くもん出版'},
      {id: 31, publisher: 'クレヨンハウス'}, {id: 32, publisher: 'グランまま社'}, {id: 33, publisher: '幻冬舎'},
      {id: 34, publisher: '好学社'}, {id: 35, publisher: '佼成出版社'}, {id: 36, publisher: '講談社'},
      {id: 37, publisher: '国書刊行会'}, {id: 38, publisher: '国土社'}, {id: 39, publisher: 'こぐま社'},
      {id: 40, publisher: '子どもの未来社'}, {id: 41, publisher: '小峰書店'}, {id: 42, publisher: 'ゴブリン書房'},
      {id: 43, publisher: '朔北社'}, {id: 44, publisher: 'サニーサイドブックス'}, {id: 45, publisher: 'サンクチュアリ出版'},
      {id: 46, publisher: 'サンマーク出版'}, {id: 47, publisher: 'さ・え・ら書房'}, 
      {id: 48, publisher: '視覚デザイン研究所'}, {id: 49, publisher: '至光社'}, {id: 50, publisher: '集英社'},
      {id: 51, publisher: '主婦の友社'}, {id: 52, publisher: '小学館'}, {id: 53, publisher: '新星出版社'},
      {id: 54, publisher: '新日本出版社'}, {id: 55, publisher: 'ジャムハウス'}, {id: 56, publisher: '鈴木出版'},
      {id: 57, publisher: '瑞雲社'}, {id: 58, publisher: '世界文化社'}, {id: 59, publisher: 'そうえん社'},
      {id: 60, publisher: '創元社'}, {id: 61, publisher: '草土文化'}, {id: 62, publisher: '辰巳出版'},
      {id: 63, publisher: '玉川大学出版部'}, {id: 64, publisher: '大日本図書'}, {id: 65, publisher: 'ダイヤモンド社'}, 
      {id: 66, publisher: '大和書房'}, {id: 67, publisher: '小さい書房'}, {id: 68, publisher: '汐文社'},
      {id: 69, publisher: 'TOブックス'}, {id: 70, publisher: 'Discover21'}, {id: 71, publisher: '東京書籍'},
      {id: 72, publisher: '東京書店'}, {id: 73, publisher: '冬春創社'}, {id: 74, publisher: '徳間書店'},
      {id: 75, publisher: '童心社'}, {id: 76, publisher: '童話屋'}, {id: 77, publisher: '永岡書店'},
      {id: 78, publisher: '長崎出版'}, {id: 79, publisher: '西村書店'}, {id: 80, publisher: '農山漁村文化協会'},
      {id: 81, publisher: '白泉社'}, {id: 82, publisher: '早川書房'}, {id: 83, publisher: 'バベルプレス'},
      {id: 84, publisher: 'パイ インターナショナル'}, {id: 85, publisher: 'ひかりのくに'}, {id: 86, publisher: 'ひさかたチャイルド'},
      {id: 87, publisher: '評論社'}, {id: 88, publisher: 'BL出版'}, {id: 89, publisher: 'PHP研究所'},
      {id: 90, publisher: '風濤社'}, {id: 91, publisher: 'フェリシモ出版'}, {id: 92, publisher: '福音館書店'},
      {id: 93, publisher: '冨山房'}, {id: 94, publisher: '双葉社'}, {id: 95, publisher: 'フレーベル館'},
      {id: 96, publisher: 'ブロンズ新社'}, {id: 97, publisher: '文化出版局'}, {id: 98, publisher: '文溪堂'},
      {id: 99, publisher: '文研出版'}, {id: 100, publisher: '平凡社'}, {id: 101, publisher: 'ペンギン社'}, 
      {id: 102, publisher: 'ほるぷ出版'}, {id: 103, publisher: 'ポプラ社'}, {id: 104, publisher: 'マイクロマガジン社'},
      {id: 105, publisher: 'MIKI HOUSE'}, {id: 106, publisher: '光村教育図書'}, {id: 107, publisher: 'ミルブックス'},
      {id: 108, publisher: 'メディアファクトリー'}, {id: 109, publisher: 'らんか社'}, {id: 110, publisher: '理論社'},
      {id: 111, publisher: 'リーブル'}, {id: 112, publisher: 'ロクリン社'}, {id: 113, publisher: 'その他'}
  ]
  include ActiveHash::Associations
  has_many :books
end